#!/bin/bash

[ -z "$DISPLAY" ] && export DISPLAY=":99.0"
echo DISPLAY is $DISPLAY

XID="xvfb-${DISPLAY//[\:\.]/}"

daemon="daemon -n $XID -o /var/log/$XID.log"
vdaemon="daemon -n $XID-vnc -o /var/log/$XID-vnc.log"

password=acre
vnc_port=9900

cmd="Xvfb $DISPLAY -screen 0 1280x1024x24"

[ -z "$OUTPUT_DIR" ] && OUTPUT_DIR=.

case $1 in
    start)
        echo starting xvfb
        $daemon -- $cmd
        sleep 3
        $vdaemon -- x11vnc -forever -passwd $password -shared -rfbport $vnc_port -display $DISPLAY
        ;;
    stop)
        echo stopping xvfb
        $daemon --stop
        $vdaemon --stop
        ;;
    restart)
        $daemon --stop
        $vdaemon --stop
        $daemon -- $cmd
        $vdaemon -- x11vnc -forever -passwd $password -shared -rfbport $vnc_port -display $DISPLAY
        ;;
    *)
        echo unknown command
        ;;
esac
