name: Makefile CI

on:
  push:
    branches: [ branches/docker ]
  pull_request:
    branches: [ branches/docker ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: build docker image
        run:  |
          make acre.image
          docker tag acre ghcr.io/realtimeprojects/acre:latest

      - name: Log in to Docker Hub
        run: docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push docker image
        run:  docker push ghcr.io/realtimeprojects/acre:latest

